name: Release

on:
  push:
    tags:
      - 'v*'
    branches:
      - 'main'
      - 'ecr_docker_dep'

jobs:
  release:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24.7'
        
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_FORKLIFTPROD_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_FORKLIFTPROD_SECRET_KEY }}
        aws-region: us-west-2
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build and push
      uses: docker/build-push-action@v5.1.0
      with:
        push: true
        context: build/Dockerfile
        tags: ${{ steps.login-ecr.outputs.registry }}/prod-serp-collector:${{ github.sha }},${{ steps.login-ecr.outputs.registry }}/prod-serp-collector:latest 
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max

    - name: API:- Output image tag
      id: build-image
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: caterpillar
        IMAGE_TAG: ${{ github.sha }}
      run: |
        echo "::set-output name=image::$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"

    - name: Deploy to ECR
      uses: aws-actions/amazon-ecr-deploy-image@v1
      with:
        image-tag: ${{ steps.build-image.outputs.image }}
        repository-name: ${{ steps.build-image.outputs.repository }}
        region: us-west-2
        skip-ci: true
        force-new-deployment: true